"""Create sounds tables

Revision ID: c97066a6d6aa
Revises: 
Create Date: 2024-10-28 19:35:54.977874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from model import Sound
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
revision: str = 'c97066a6d6aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('default_volume', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = Session(bind=bind)
    sounds = [
    Sound(id="1", name="rain",display_name="Rain",icon="🌧️",file_path="/static/sounds/rain.mp3"),
    Sound(id="2", name="forest",display_name="Forest",icon="🌲",file_path="/static/sounds/forest.mp3"),
    Sound(id="3", name="fire",display_name="Fire",icon="🔥",file_path="/static/sounds/fire.mp3")
    ]
    session.add_all(sounds)
    session.commit()
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sounds')
    # ### end Alembic commands ###
